services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dentalclinic
    restart: always

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:

